name: get_pubs 

on: 
  push: 
    paths:
      - _publications

jobs: 
  build: 
    runs-on: ubuntu-latest
  permissions:
     # Give the default GITHUB_TOKEN write permission to commit and push the
     # added or changed files to the repository.
    contents: write
  steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python
        with:
          python-version: '3.11'
          run: |
            python -m pip install --upgrade pip 
            pip install pandas pyyaml 
          ref: 
            main
      - name: execute python script 
        run: |
          python3 collect_pub_files.py
      - name :  commit updated files
        uses : actions4git/setup-git@v1   
        run : | 
          git add "_data/pub_list.csv"
          git commit -m "update publication list"
          git push
